<Project>
	<!-- Par défaut, chaque projet build dans son dossier bin\ -->
	<PropertyGroup>
		<OutputPath>bin\</OutputPath>
	</PropertyGroup>

	<!-- Le projet UtilitySlots sort directement dans BepInEx/plugins -->
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'UtilitySlots'">
		<OutputPath>$(BepInExDir)\plugins\UtilitySlots\</OutputPath>
	</PropertyGroup>
</Project>
