<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <SolutionDirNoSlash>$([System.String]::Copy('$(SolutionDir)').TrimEnd('\'))</SolutionDirNoSlash>
  </PropertyGroup>

  <Target Name="GenerateTreeAndZip" AfterTargets="Build;Rebuild">
	  <Exec Command='powershell -NoProfile -ExecutionPolicy Bypass -File "$(SolutionDir)BuildTools_Snapshot.ps1" -SolutionDir:"$(SolutionDirNoSlash)" -OutputDir:"C:\Users\thiba\Desktop\DocGPTAyaMods" -ZipName:"AyaModsSnapshot.zip"' />
  </Target>
	
</Project>