<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<AssemblyName>UtilitySlots</AssemblyName>
		<RootNamespace>UtilitySlots</RootNamespace>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AyaCoreMod\AyaCoreMod.csproj" />
	</ItemGroup>
</Project>